
spring:
  ## 数据库
  datasource:
    username: root
    password: Gzk12345#
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/channel?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8

  ##file 上传文件大小
  servlet:
    multipart:
      max-request-size: 3000MB
      max-file-size: 3000MB


  ##freemarker
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/templates

## mybatis
mybatis:
  ## mapper.xml 放置目录
  mapper-locations: classpath:mapper/*.xml
  ## 驼峰转化
  configuration:
    map-underscore-to-camel-case: true

## 日志
logging:
  level:
    com:
      xg:
        mapper: debug


file:
  staticAccessPath: /getFile/**
  uploadFolder: /Users/didi/Desktop/


